-- Query del Ejercicio #1
SELECT CU.CUSTOMER_ID, CU.FIRST_NAME, CU.LAST_NAME, R.RENTAL_DATE::DATE, COUNT(*) AS total_rent
FROM CUSTOMER CU
JOIN RENTAL R ON CU.CUSTOMER_ID=R.CUSTOMER_ID
GROUP BY CU.FIRST_NAME, CU.LAST_NAME, R.RENTAL_DATE::DATE, CU.CUSTOMER_ID
HAVING COUNT(*)>1
ORDER BY  CU.FIRST_NAME, CU.CUSTOMER_ID ASC

-- Query del Ejercicio #2
SELECT TO_CHAR (R.RENTAL_DATE,'YYYY-MM') AS rental_month, CO.COUNTRY, COUNT(*) AS rental_count
FROM RENTAL R
JOIN CUSTOMER CU ON R.CUSTOMER_ID=CU.CUSTOMER_ID
JOIN ADDRESS AD ON CU.ADDRESS_ID=AD.ADDRESS_ID
JOIN CITY CI ON AD.CITY_ID=CI.CITY_ID
JOIN COUNTRY CO ON CI.COUNTRY_ID=CO.COUNTRY_ID
GROUP BY TO_CHAR(R.RENTAL_DATE,'YYYY-MM'), CO.COUNTRY
ORDER BY TO_CHAR(R.RENTAL_DATE,'YYYY-MM'), CO.COUNTRY


-- Query del Ejercicio #3
SELECT EXTRACT(YEAR FROM PA.PAYMENT_DATE) ||'/'|| 
EXTRACT(MONTH FROM PA.PAYMENT_DATE) AS "FECHA_DE_AÑO_Y_MES",
       ST.STAFF_ID AS "CÓDIGO_DE_EMPLEADO",
       CONCAT(ST.FIRST_NAME, ' ', ST.LAST_NAME) AS "NOMBRE COMPLETO DEL EMPLEADO",
       SU.CITY AS "CIUDAD DE LA SUCURSAL",
       SUM(PA.AMOUNT) AS "MONTO TOTAL PAGADO"
FROM PAYMENT PA
JOIN STAFF ST ON PA.STAFF_ID = ST.STAFF_ID
JOIN STORE S ON ST.STORE_ID = S.STORE_ID
JOIN ADDRESS A ON S.ADDRESS_ID = A.ADDRESS_ID
JOIN CITY SU ON A.CITY_ID = SU.CITY_ID
GROUP BY EXTRACT(YEAR FROM PA.PAYMENT_DATE), EXTRACT(MONTH FROM PA.PAYMENT_DATE), ST.STAFF_ID, ST.FIRST_NAME, ST.LAST_NAME, SU.CITY
ORDER BY "FECHA_DE_AÑO_Y_MES", "CÓDIGO_DE_EMPLEADO";

-- Query del Ejercicio #4
SELECT EXTRACT(MONTH FROM R.RENTAL_DATE) AS MONTH,COUNT(*) RENTAS_TOTALES, SUM(PA.AMOUNT) AS TOTAL
FROM RENTAL R
JOIN PAYMENT PA ON R.RENTAL_ID = PA.RENTAL_ID
GROUP BY MONTH

